# Generated by Django 5.0.6 on 2024-05-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='original_images/')),
                ('noisy_image', models.ImageField(blank=True, null=True, upload_to='noisy_images/')),
                ('denoised_image', models.ImageField(blank=True, null=True, upload_to='denoised_images/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('selected_noise', models.CharField(max_length=100)),
                ('detected_noise', models.CharField(blank=True, max_length=100, null=True)),
                ('filter_applied', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
