# Generated by Django 5.0.6 on 2024-05-28 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0002_remove_image_denoised_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='noisy_image_generated',
            field=models.ImageField(blank=True, null=True, upload_to='noisy_images/'),
        ),
    ]
