# Generated by Django 5.0.6 on 2024-06-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0003_image_noisy_image_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='filtered_image',
            field=models.ImageField(blank=True, null=True, upload_to='filtered_images/'),
        ),
    ]
